//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _APPMSGHANDLER_H_
#define _APPMSGHANDLER_H_

#include <TinyCLR_Interop.h>
struct Library_AppMsgHandler_Samraksh_VirtualFence_Components_AppMsgHandler
{
    static const int FIELD_STATIC___retriedPackets = 0;
    static const int FIELD_STATIC___lcd = 1;
    static const int FIELD_STATIC___MACID = 2;


    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_AppMsgHandler;

#endif  //_APPMSGHANDLER_H_
