//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _SAMRAKSH_VIRTUALFENCE_RELAYNODE_H_
#define _SAMRAKSH_VIRTUALFENCE_RELAYNODE_H_

#include <TinyCLR_Interop.h>
struct Library_Samraksh_VirtualFence_RelayNode_Samraksh_VirtualFence_Program
{
    static const int FIELD_STATIC___lcd = 0;


    //--//

};

struct Library_Samraksh_VirtualFence_RelayNode_Samraksh_VirtualFence_Resources
{
    static const int FIELD_STATIC__manager = 1;


    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_VirtualFence_RelayNode;

#endif  //_SAMRAKSH_VIRTUALFENCE_RELAYNODE_H_
