//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _SAMRAKSH_VIRTUALFENCE_BASENODE_H_
#define _SAMRAKSH_VIRTUALFENCE_BASENODE_H_

#include <TinyCLR_Interop.h>
struct Library_Samraksh_VirtualFence_BaseNode_Samraksh_VirtualFence_Base
{
    static const int FIELD_STATIC___lcd = 0;
    static const int FIELD_STATIC___baseLiveMsgNum = 1;


    //--//

};

struct Library_Samraksh_VirtualFence_BaseNode_Samraksh_VirtualFence_Base__<>c__DisplayClass1
{
    static const int FIELD__serialComm = 1;


    //--//

};

struct Library_Samraksh_VirtualFence_BaseNode_Samraksh_VirtualFence_Resources
{
    static const int FIELD_STATIC__manager = 2;


    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_VirtualFence_BaseNode;

#endif  //_SAMRAKSH_VIRTUALFENCE_BASENODE_H_
