//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _SAMRAKSH_VIRTUALFENCE_CLIENTNODE_H_
#define _SAMRAKSH_VIRTUALFENCE_CLIENTNODE_H_

#include <TinyCLR_Interop.h>
struct Library_Samraksh_VirtualFence_ClientNode_Samraksh_VirtualFence_Program
{
    static const int FIELD_STATIC__SendPacketInterval = 0;
    static const int FIELD_STATIC___lcd = 1;


    //--//

};

struct Library_Samraksh_VirtualFence_ClientNode_Samraksh_VirtualFence_Resources
{
    static const int FIELD_STATIC__manager = 2;


    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_VirtualFence_ClientNode;

#endif  //_SAMRAKSH_VIRTUALFENCE_CLIENTNODE_H_
